Weather App/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace Weather_App.Pages {
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger) {
            _logger = logger;
        }

        public void OnGet() {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Weather App/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Weather.BusinessLogic.Interfaces;
using Weather.BusinessLogic.Services;
using Weather.BusinessLogic.Classes;
using System.Linq;

namespace Weather_App.Pages {
    public class IndexModel : PageModel {
        private readonly ILogger<IndexModel> _logger;
        private IViewWeatherReports _weatherReportRepository;
        public WeatherReport lastReport = new WeatherReport();
        public string reportImage = string.Empty;
        const string red = "#EE4B2B";
        const string grey = "#808080";
        public string temperatureColour = grey;
        public string cloudCoverColour = grey;
        public string airHumidityColour = grey;
        public string windSpeedColour = grey;

        public IndexModel(ILogger<IndexModel> logger, IViewWeatherReports weatherReportRepository) {
            _logger = logger;
            _weatherReportRepository = weatherReportRepository;
        }

        public async Task OnGet() {
            var response = await _weatherReportRepository.GetLastXWeatherReports(1);
            var report = response.FirstOrDefault();
            if (report != null)
                setLastReport(report);
        }

        public async Task OnPostButton() {
            var report = await _weatherReportRepository.GetWeatherReport();
            setLastReport(report);
        }

        private void setLastReport(WeatherReport report) {
            lastReport = report;
            temperatureColour = report.Temperature > 18 ? grey : red;
            cloudCoverColour = report.CloudCover < 30 ? grey : red;
            airHumidityColour = report.AirHumidity < 60 ? grey : red;
            windSpeedColour = report.WindSpeed < 12 ? grey : red;
            if (report.Temperature > 18 && report.CloudCover < 30 && report.AirHumidity < 60 && report.WindSpeed < 12) {
                reportImage = "https://media4.giphy.com/media/MNmyTin5qt5LSXirxd/giphy.gif?cid=ecf05e47pvdqkbzqkciesxfqz00u09d5uuy5kik38rqbrwjv&rid=giphy.gif&ct=g";
            } else {
                reportImage = "https://media3.giphy.com/media/xTcnTehwgRcbgymhTW/giphy.gif?cid=ecf05e47lkr1wl44lzzcembvmbc4s13t3bzbq0dg1hysbg4c&rid=giphy.gif&ct=g";
            }
        }
    }
}

Weather App/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Weather_App.Pages {
    public class PrivacyModel : PageModel {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger) {
            _logger = logger;
        }

        public void OnGet() {
        }
    }
}

Weather App/Pages/Index.cshtml
@page
@using Weather.BusinessLogic.Interfaces
@model IndexModel
@inject IWeatherReportRepository weatherReportRepository
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <form asp-page-handler="button" method="post">
        <button class="btn btn-default" style="border: 2px solid #868B94;
                                                  background-color: white;
                                                  color: black;
                                                  padding: 14px 28px;
                                                  font-size: 16px;
                                                  cursor: pointer;">Get New Report</button>
    </form>
</div>

<section class="vh-100">
    <div class="container py-5">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-md-10 col-lg-8 col-xl-8">
                <div class="card" style="color: #4B515D; border-radius: 35px;">
                    <div class="card-body p-4">
                        <div class="d-flex">
                            <h6 class="flex-grow-1"> @Html.DisplayFor(index => index.lastReport.Location)</h6>
                            <h6> @Html.DisplayFor(index => index.lastReport.TimeOfMeasurement)</h6>
                        </div>

                        <div class="d-flex flex-column text-center mt-5 mb-4">
                            <h6 class="display-4 mb-0 font-weight-bold" style="color: @Html.DisplayFor(index => index.temperatureColour);">  @Html.DisplayFor(index => index.lastReport.Temperature)°C </h6>
                            <span class="small" style="color: #868B94">@Html.DisplayFor(index => index.lastReport.WeatherDescription)</span>
                        </div>

                        <div class="d-flex align-items-center">
                            <div class="flex-grow-1" style="font-size: 1rem;">
                                <div><span style="color: @Html.DisplayFor(index => index.windSpeedColour);" class="ms-1">Wind Speed: @Html.DisplayFor(index => index.lastReport.WindSpeed) km/h</span></div>
                                <div><span style="color: @Html.DisplayFor(index => index.airHumidityColour);" class="ms-1">Air Humidity @Html.DisplayFor(index => index.lastReport.AirHumidity)% </span></div>
                                <div><span style="color: @Html.DisplayFor(index => index.cloudCoverColour);" class="ms-1">Cloud Cover @Html.DisplayFor(index => index.lastReport.CloudCover)</span></div>
                                <div><span style="color: #868B94;" class="ms-1">Wind Direction @Html.DisplayFor(index => index.lastReport.WindDirection)</span></div>
                            </div>
                            <div>
                                <img src="@Html.DisplayFor(index => index.reportImage)"
                                     width="380px">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</section>

Weather App/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Weather_App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Weather_App.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Weather_App</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Weather_App - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>